apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: api
      port: {{ .Values.ports.api }}
      targetPort: {{ .Values.ports.api }}
      protocol: TCP
    - name: console
      port: {{ .Values.ports.console }}
      targetPort: {{ .Values.ports.console }}
      protocol: TCP